require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe EnrollmentsController, type: :controller do
  
  before do
    @current_user = create(:user)
    sign_in(@current_user)
  end
  
  let(:institution) { create(:institution) }
  
  let(:person) { create(:person, institution: institution) }

  # This should return the minimal set of attributes required to create a valid
  # Enrollment. As you add validations to Enrollment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { grade_id: create(:grade, institution: institution).id, role: "Evangelizando" }
  }

  let(:invalid_attributes) {
    { grade_id: "", role: "" }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EnrollmentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all enrollments as @enrollments" do
      enrollment = create(:enrollment, person: person)
      get :index, {institution_id: institution.id, person_id: person.id}, valid_session
      expect(assigns(:enrollments)).to eq([enrollment])
    end
  end

  describe "GET #show" do
    it "assigns the requested enrollment as @enrollment" do
      enrollment = create(:enrollment, person: person)
      get :show, {:id => enrollment.to_param, institution_id: institution.id, person_id: person.id}, valid_session
      expect(assigns(:enrollment)).to eq(enrollment)
    end
  end

  describe "GET #new" do
    it "assigns a new enrollment as @enrollment" do
      get :new, {institution_id: institution.id, person_id: person.id}, valid_session
      expect(assigns(:enrollment)).to be_a_new(Enrollment)
    end
  end

  describe "GET #edit" do
    it "assigns the requested enrollment as @enrollment" do
      enrollment = create(:enrollment, person: person)
      get :edit, {:id => enrollment.to_param, institution_id: institution.id, person_id: person.id}, valid_session
      expect(assigns(:enrollment)).to eq(enrollment)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Enrollment" do
        expect {
          post :create, {:enrollment => valid_attributes, institution_id: institution.id, person_id: person.id}, valid_session
        }.to change(Enrollment, :count).by(1)
      end

      it "assigns a newly created enrollment as @enrollment" do
        post :create, {:enrollment => valid_attributes, institution_id: institution.id, person_id: person.id}, valid_session
        expect(assigns(:enrollment)).to be_a(Enrollment)
        expect(assigns(:enrollment)).to be_persisted
      end

      it "redirects to the created enrollment" do
        post :create, {:enrollment => valid_attributes, institution_id: institution.id, person_id: person.id}, valid_session
        expect(response).to redirect_to(institution_person_enrollment_path(institution, person, Enrollment.last))
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved enrollment as @enrollment" do
        post :create, {:enrollment => invalid_attributes, institution_id: institution.id, person_id: person.id}, valid_session
        expect(assigns(:enrollment)).to be_a_new(Enrollment)
      end

      it "re-renders the 'new' template" do
        post :create, {:enrollment => invalid_attributes, institution_id: institution.id, person_id: person.id}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        { role: "Evangelizador" }
      }

      it "updates the requested enrollment" do
        enrollment = create(:enrollment, person: person)
        put :update, {:id => enrollment.to_param, :enrollment => new_attributes, institution_id: institution.id, person_id: person.id}, valid_session
        enrollment.reload
        expect(enrollment.role).to eq("Evangelizador")
      end

      it "assigns the requested enrollment as @enrollment" do
        enrollment = create(:enrollment, person: person)
        put :update, {:id => enrollment.to_param, :enrollment => valid_attributes, institution_id: institution.id, person_id: person.id}, valid_session
        expect(assigns(:enrollment)).to eq(enrollment)
      end

      it "redirects to the enrollment" do
        enrollment = create(:enrollment, person: person)
        put :update, {:id => enrollment.to_param, :enrollment => valid_attributes, institution_id: institution.id, person_id: person.id}, valid_session
        expect(response).to redirect_to(institution_person_enrollment_path(institution, person, enrollment))
      end
    end

    context "with invalid params" do
      it "assigns the enrollment as @enrollment" do
        enrollment = create(:enrollment, person: person)
        put :update, {:id => enrollment.to_param, :enrollment => invalid_attributes, institution_id: institution.id, person_id: person.id}, valid_session
        expect(assigns(:enrollment)).to eq(enrollment)
      end

      it "re-renders the 'edit' template" do
        enrollment = create(:enrollment, person: person)
        put :update, {:id => enrollment.to_param, :enrollment => invalid_attributes, institution_id: institution.id, person_id: person.id}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested enrollment" do
      enrollment = create(:enrollment, person: person)
      expect {
        delete :destroy, {:id => enrollment.to_param, institution_id: institution.id, person_id: person.id}, valid_session
      }.to change(Enrollment, :count).by(-1)
    end

    it "redirects to the enrollments list" do
      enrollment = create(:enrollment, person: person)
      delete :destroy, {:id => enrollment.to_param, institution_id: institution.id, person_id: person.id}, valid_session
      expect(response).to redirect_to(institution_person_enrollments_url(institution, person))
    end
  end

end
